---
layout: cv
title: Adam Ulrich
---

## Director of Softare Engineering

_I’m a detail-oriented servant-leader by choice. As a passionate mentor, coach, and leader, I believe that how we do things is at least as important as what we do. I care deeply about the quality of what we deliver and consider quality the most important feature my team ships._

[adamulrich@hotmail.com](mailto:adamulrich@hotmail.com) | [LinkedIn](https://www.linkedin.com/in/adammulrich/) | [Github Projects](https://github.com/adamulrich)

<!-- https://www.monique.tech/the-art-of-markdown -->

## Education

### B.S. Software Development

`2022 - 2024`
__Brigham Young University - Idaho__, Rexburg, ID

- 4.0 GPA
- Certificates awarded in:
  - `Software Development`
  - `Web and Computer Programming`
  - `Web Development`

## Skills

- AWS and Azure knowledge/experience
- Data and database expertise
- Build/infra systems expertise
- Expert in testing and test automation
- Experience in software engineering across DEV, TEST, PM, OPS and SRE
- Recent experience in Python, Node.js, JavaScript and PHP
- Experience with .Net, VB, C#
- Extensive experience with offshoring
- Demonstrated organizational agility

## Experience

### Dremio Corportation

 _Santa Clara, CA_, `Oct 2023 to present`

 __Director of Engineering, Developer Experience__, `2023 - present`.
 Remotely based in the Seattle, WA area, responsibilities included managing of team of 25 that oversee build systems, CI/CD, QA, performance infrastructure, branch health and release operations.

### Tableau Software/ Salesforce

 _Seattle, WA_, `Sep 2018 – Oct 2023`

__Senior Engineering Manager, Developer Productivity & Experience__, `2020-2023`. 
Primary responsibilities included build and infrastructure systems, testing pipelines, cloud lab infrastructure and developer tooling.  Accomplishments include cloud cost reduction, patch management, tableau server as a service, vulnerability management, and reducing noise in service health signals.

__Senior Engineering Manager, Tableau Prep Builder__, `2018-2020`
Oversaw the delivery of data cleaning and data preparation features.

### Microsoft

_Redmond, WA_, `Mar 1996 – Sep 2018`

__Principal SWE Manager, SRE Manager and PM, Microsoft Dynamics__, `2016-2018`
Responsible for Tier 3 support team for Dynamics Online, including email services and performance testing. Extensive use of Azure. Drove transition to Agile Methodology for team.

__Principal Test Manager, Microsoft Physical Stores__, `2011-2016`
Responsible for all testing in Microsoft Stores, including POS and CRM, including integrations with dozens of other systems. Extensive hardware and software testing, along with offshore team management.

__Principal Test Manager, Microsoft Expression Blend & Design__, `2003-2011`
Shipped Expression Blend and Design, 1, 2, 3, and 4.  Awarded 3 patents for test automation. 3x DevDiv Mgr. Excellence Award. Led Expression offshoring, driving cost reductions and quality improvements.

__Senior Test Lead, STE, SDET, Developer Division__, `1996-2002`
Primary technical focus on database metadata and visual design. Responsible for test automation system design and implementation.

### Patents

- [Patent `7,823,132`: Loosely Coupled Comprehensive Verification](https://ppubs.uspto.gov/dirsearch-public/print/downloadPdf/7823132)
- [Patent `7,457,989`: Execution Behavior Manager](https://ppubs.uspto.gov/dirsearch-public/print/downloadPdf/7457989)
- [Patent `7,398,514`: Test Automation Stack Layering](https://ppubs.uspto.gov/dirsearch-public/print/downloadPdf/7398514)

<!-- ### Footer Last updated: Feb 2024 -->
